spring.application.name=dyhouduan
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.servlet.multipart.resolve-lazily=true
server.tomcat.connection-timeout=120000
spring.mvc.async.request-timeout=120000
